### ISSUE TITLE
Fehler beim Start von Home Assistant

### ISSUE THREAD

**Issue by nobbilie** [john30/ebusd#1347]
### Description

Ich habe folgend Fehlermeldung beim start von Home Assistant

Logger: homeassistant.setup
Quelle: setup.py:416
Erstmals aufgetreten: 14:18:01 (1 Vorkommnisse)
Zuletzt protokolliert: 14:18:01

Error during setup of component ebusd
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/ebusdpy/ebusdpy.py", line 14, in init
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/ebusd/__init__.py", line 69, in setup
    ebusdpy.init(server_address)
  File "/usr/local/lib/python3.12/site-packages/ebusdpy/ebusdpy.py", line 18, in init
    raise EBusError(socket.error)
ebusdpy.ebusdpy.EBusError: <class 'OSError'>

Was kann das sein und wie behebe ich es? 

### Actual behavior

Kein vollständiger Boot der Integration in Home Assistant - Werte werden aber via MQTT übermittelt

### Expected behavior

Die EbusD Integration startet nicht vollständig, was sie aber tun sollte.

### ebusd version

23.2

### ebusd arguments

n.A.

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

x64

### Dockerized

None

### Hardware interface

Adapter Shield v5 via USB

### Related integration

MQTT Home Assistant via mqtt-hassio.cfg

### Logs

Logger: homeassistant.setup
Quelle: setup.py:416
Erstmals aufgetreten: 14:18:01 (1 Vorkommnisse)
Zuletzt protokolliert: 14:18:01

Error during setup of component ebusd
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/ebusdpy/ebusdpy.py", line 14, in init
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/ebusd/__init__.py", line 69, in setup
    ebusdpy.init(server_address)
  File "/usr/local/lib/python3.12/site-packages/ebusdpy/ebusdpy.py", line 18, in init
    raise EBusError(socket.error)
ebusdpy.ebusdpy.EBusError: <class 'OSError'>

**Comment by john30** [comment]
not an ebusd issue, but related to the HA addon, so ask the author of that one instead:
https://github.com/home-assistant/core/tree/dev/homeassistant/components/ebusd
