### ISSUE TITLE
Wrong writable entity announcements for HA

### ISSUE THREAD

**Issue by SergioRius** [john30/ebusd#803]
### Description

This is a "remake" of the previous bug: [709](https://github.com/john30/ebusd/issues/709)

Configuration parameters for "min", "max" and "step" are wrong and prevent HA to import or continue to show those entities.
Recently updated to v23.1.23.1 that introduced a change in `mqtt-hassio.cfg`. Before I had patched the "max" variable to 60 and that allowed to import entities to HA. With the upgrade those entities disappeared from HA.

### Actual behavior

The new config schema publishes entities to discover with huge amounts in "min", "max" and "step" that throws error while importing those entities in HA:

```json
{
  "unique_id":"ebusd_bass2_Hc1MinFlowTempDesired_tempv",
  "name":"ebusd bass2 Hc1MinFlowTempDesired tempv",
  "device":{
   "identifiers":"ebusd_bass2",
   "manufacturer":"ebusd.eu",
   "name":"ebusd bass2",
   "via_device":"ebusd",
   "sw_version":"23.1",
   "suggested_area":"Heating"
  },
  "value_template":"{{value_json[\"tempv\"].value}}",
  "state_topic":"ebusd/bass2/Hc1MinFlowTempDesired",
  "command_topic":"ebusd/bass2/Hc1MinFlowTempDesired/set",
  "min":-1.70141e+38,
  "max":1.70141e+38,
  "step":1.4013e-45,
  "unit_of_measurement":"°C",
  "device_class":"temperature"
 }
```

### Expected behavior

Patching the following lines in `/etc/ebusd/mqtt-hassio.cfg` fixes the problem (for some entities, that I know).

```bash
# HA integration: optional variable with the minimum numeric value
min_number ?= ,
  "min":0
#  "min":%min

# HA integration: optional variable with the maximum numeric value
max_number ?= ,
  "max":60
#  "max":%max

# HA integration: optional variable with the numeric step value
step_number ?= ,
  "step":1
#  "step":%step
```

### ebusd version

23.1

### ebusd arguments

--scanconfig --pollinterval=10 --accesslevel=* --configpath=/home/pi/ebusd-configuration/latest/en/ --mqttint=/etc/ebusd/mqtt-hassio.cfg --mqttvar=filter-direction=r|u|^w --mqttjson --mqtthost=10.1.5.43 --mqttport=1883

### Operating system

Debian 11 (Bullseye) / Ubuntu 20-21 / Raspbian 11 / Raspberry Pi OS 11 (including lite)

### CPU architecture

x64

### Dockerized

None

### Hardware interface

other

### Related integration

MQTT Home Assistant via mqtt-hassio.cfg

### Logs

Does not throw error in the ebusd logs.

**Comment by edudele** [comment]
I have the same problem:

Show in log Home Assitant,
Values of MIN, MAX y STEP they are not valid:

**'min': -1.70141e+38
'max': -1.70141e+38
'step': 1.4013e-45**

```
2023-01-09 15:57:11.040 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_number_mqtt': ({'unique_id': 'ebusd_basv0_z3ActualRoomTempDesired_tempv', 'name': 'ebusd basv0 z3ActualRoomTempDesired tempv', 'device': {'identifiers': 'ebusd_basv0', 'manufacturer': 'ebusd.eu', 'name': 'ebusd basv0', 'via_device': 'ebusd', 'sw_version': '22.4', 'suggested_area': 'Heating'}, 'value_template': '{{value_json["tempv"].value}}', 'state_topic': 'ebusd/basv0/z3ActualRoomTempDesired', 'command_topic': 'ebusd/basv0/z3ActualRoomTempDesired/set', 'min': -1.70141e+38, 'max': '-1.70141e+38', 'step': 1.4013e-45, 'unit_of_measurement': '°C', 'device_class': 'temperature', 'platform': 'mqtt'},)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 331, in async_discover
config: DiscoveryInfoType = discovery_schema(discovery_payload)
File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 232, in __call__
return self._exec((Schema(val) for val in self.validators), v)
File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
raise e if self.msg is None else AllInvalid(self.msg, path=path)
File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 351, in _exec
v = func(v)
File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
return schema(data)
File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
return base_validate(path, iteritems(data), out)
File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: value must be at least 0.001 for dictionary value @ data['step']
```

**Comment by john30** [comment]
this is due to the datatype EXP used by these messages which supports extreme values.
hm, need to think what to do with those or remove min/max/step for EXP completely

**Comment by john30** [comment]
a workaround for now is to exclude messages with an EXP field in it or remove the min/max/step values from the hassio cfg
