### ISSUE TITLE
Exception raised when updating state of sensor.ebusd_scan, topic: 'ebusd/global/scan' with payload: b'"finished"'

### ISSUE THREAD

**Issue by mf76130** [john30/ebusd#930]
### Description

When updating data.

### Actual behavior

sensor-ebusd_scan gets not updated in Home Assistant as it expects a numeric format but gets a string.

### Expected behavior

sensor-ebusd_scan set to string

### ebusd version

23.1

### ebusd arguments

--configpath=/etc/ebusd/ -d /dev/ttyUSB0 --latency=0 --pollinterval=120 --loglevel=debug --mqttint=/etc/ebusd/mqtt-hassio.cfg --mqttjson --mqtthost=192.168.0.17 --mqttport=1883 --mqttuser=.......

### Operating system

Debian 11 (Bullseye) / Ubuntu 20-21 / Raspbian 11 / Raspberry Pi OS 11 (including lite)

### CPU architecture

x64

### Dockerized

None

### Hardware interface

adapter 5 via USB

### Related integration

MQTT Home Assistant via mqtt-hassio.cfg

### Logs

Logger: homeassistant.components.mqtt.models
Source: components/sensor/__init__.py:585
Integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 04:25:55 (3 occurrences)
Last logged: 05:19:10

Exception raised when updating state of sensor.ebusd_scan, topic: 'ebusd/global/scan' with payload: b'"finished"'
Exception raised when updating state of sensor.ebusd_scan, topic: 'ebusd/global/scan' with payload: b'"running"'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: '"finished"'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 585, in state
    raise ValueError(
ValueError: Sensor sensor.ebusd_scan has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '"finished"' (<class 'str'>)

**Comment by mf76130** [comment]
updated mqtt-hassio.cfg on my ebusd hub, that fixed it
