### ISSUE TITLE
HA MQTT global/scan error

### ISSUE THREAD

**Issue by BeFygo** [john30/ebusd#946]
### Description

MQTT message for "scan" is received but not read correct by Home Assistant resulting in "unknow" status.

```
Message 57 received on Vaillant/global/scan at 10:48:
"finished"
QoS: 0 - Retain: false
```

### Actual behavior

![image](https://github.com/john30/ebusd/assets/72655961/5901cc9a-4e55-48bf-8e81-bebe71395eed)

### Expected behavior

HA showing "finished" state

### ebusd version

23.1

### ebusd arguments

version: "3.8" services:      ebusd:     container_name: Ebusd     image: john30/ebusd:latest #    volumes:      ports:       - 8888:8888       # when enabling the HTTP port, add it to the published ports as well:       #- 8080:8080     #devices:       # when using an USB device, make sure to hand it in to the container like this:       #- /dev/ttyUSB0:/dev/ttyUSB0     environment:       # Device options:              EBUSD_OPTS: "--scanconfig -d ens:192.168.0.79:9999"              # Use DEV as eBUS device ("enh:DEVICE" or "enh:IP:PORT" for enhanced device, "ens:DEVICE" for enhanced high speed       # serial device, "DEVICE" for serial device, or "[udp:]IP:PORT" for network device)       EBUSD_DEVICE: "ens:192.168.0.79:9999"       # Skip serial eBUS device test       #EBUSD_NODEVICECHECK: ""       # Only read from device, never write to it       #EBUSD_READONLY: ""       # Send an initial escape symbol after connecting device       #EBUSD_INITSEND: ""       # Extra transfer latency in ms       EBUSD_LATENCY: 50        # Message configuration options:        # Read CSV config files from PATH (local folder or HTTPS URL)       #EBUSD_CONFIGPATH: "/path/to/local/configs"       EBUSD_CONFIGPATH: "https://cfg.ebusd.eu/"       # Pick CSV config files matching initial scan (ADDR="none" or empty for no initial scan message, "full" for full       # scan, or a single hex address to scan, default is broadcast ident message).       #EBUSD_SCANCONFIG: "--scanconfig"       # Prefer LANG in multilingual configuration files       #EBUSD_CONFIGLANG: "en"       # Poll for data every SEC seconds (0=disable)       EBUSD_POLLINTERVAL: 15       # Use CA FILE for checking certificates (uses defaults, "#" for insecure)       #EBUSD_CAFILE: "/path/to/cafile"       # Use CA PATH for checking certificates (uses defaults)       #EBUSD_CAPATH: "/path/to/cafiles"        # eBUS options:        # Use ADDR as own bus address       #EBUSD_ADDRESS: ff       # Actively answer to requests from other masters       #EBUSD_ANSWER: ""       # Stop bus acquisition after MSEC ms       #EBUSD_ACQUIRETIMEOUT: 10       # Retry bus acquisition COUNT times       #EBUSD_ACQUIRERETRIES: 3       # Repeat failed sends COUNT times       #EBUSD_SENDRETRIES: 2       # Expect a slave to answer within MSEC ms       #EBUSD_RECEIVETIMEOUT: 50       # Expect COUNT masters on the bus, 0 for auto detection       #EBUSD_NUMBERMASTERS: 0       # Enable AUTO-SYN symbol generation       #EBUSD_GENERATESYN: ""        # Daemon options:        # Set default access level to LEVEL ("*" for everything)       EBUSD_ACCESSLEVEL: "*"       # Read access control list from FILE       #EBUSD_ACLFILE: "/path/to/aclfile"       # Enable hex command       #EBUSD_ENABLEHEX: ""       # Enable define command       #EBUSD_ENABLEDEFINE: ""       # PID file name (only for daemon)       #EBUSD_PIDFILE: "/var/run/ebusd.pid"       # Listen for command line connections on PORT       EBUSD_PORT: 8888       # Listen for command line connections on 127.0.0.1 interface only       #EBUSD_LOCALHOST: ""       # Listen for HTTP connections on PORT, 0 to disable       #EBUSD_HTTPPORT: 8080       # Path for HTML files served by HTTP port       #EBUSD_HTMLPATH: "/var/ebusd/html"       # Set automatic update check to MODE (on|off)       #EBUSD_UPDATECHECK: "on"        # Log options:        # Write log to FILE (only for daemon, empty string for using syslog)       #EBUSD_LOGFILE: "/var/log/ebusd.log"       # Only write log for matching AREA(S) below or equal to LEVEL (alternative to EBUSD_LOGAREAS/EBUSD_LOGLEVEL, may       # be used multiple times)       #EBUSD_LOG: "all:notice"       # Only write log for matching AREA(S): main|network|bus|update|other|all       #EBUSD_LOGAREAS: "all"       # Only write log below or equal to LEVEL: error|notice|info|debug       #EBUSD_LOGLEVEL: "notice"        # Raw logging options:        # Log messages or all received/sent bytes on the bus       #EBUSD_LOGRAWDATA: ""       # Write raw log to FILE       #EBUSD_LOGRAWDATAFILE: "/var/log/ebusd.log"       # Make raw log file no larger than SIZE kB       #EBUSD_LOGRAWDATASIZE: 100        # Binary dump options:        # Enable binary dump of received bytes       #EBUSD_DUMP: ""       # Dump received bytes to FILE       #EBUSD_DUMPFILE: "/tmp/ebusd_dump.bin"       # Make dump file no larger than SIZE kB       #EBUSD_DUMPSIZE: 100       # Flush each byte       #EBUSD_DUMPFLUSH: ""        # MQTT options:        # Connect to MQTT broker on HOST       EBUSD_MQTTHOST: "192.168.0.52"       # Connect to MQTT broker on PORT (usually 1883), 0 to disable       EBUSD_MQTTPORT: 1883       # Set client ID for connection to MQTT broker       EBUSD_MQTTCLIENTID: "ebusd_vaillant"       # Connect as USER to MQTT broker (no default)       EBUSD_MQTTUSER: "user"       # Use PASSWORD when connecting to MQTT broker (no default)       EBUSD_MQTTPASS: "*****"       # Use MQTT TOPIC (prefix before /%circuit/%name or complete format)       EBUSD_MQTTTOPIC: "Vaillant"       # Use TOPIC for global data (default is "global/" suffix to mqtttopic prefix)       #EBUSD_MQTTGLOBAL: "ebusd/global/"       # Retain all topics instead of only selected global ones       #EBUSD_MQTTRETAIN: ""       # Set the QoS value for all topics (0-2)       #EBUSD_MQTTQOS: 0       # Read MQTT integration settings from FILE (no default)       EBUSD_MQTTINT: "/etc/ebusd/mqtt-hassio.cfg"       # Add variable(s) to the read MQTT integration settings       #EBUSD_MQTTVAR: "key=value"       # Publish in JSON format instead of strings, optionally in short (value directly below field key)       EBUSD_MQTTJSON: ""       # Publish all available attributes       #EBUSD_MQTTVERBOSE: ""       # Log library events       #EBUSD_MQTTLOG: ""       # Use protocol VERSION       #EBUSD_MQTTVERSION: "3.1"       # Ignore invalid parameters during init (e.g. for DNS not resolvable yet)       #EBUSD_MQTTIGNOREINVALID: ""       # Whether to only publish changed messages instead of all received       #EBUSD_MQTTCHANGES: ""       # Use CA file or dir (ending with '/') for MQTT TLS (no default)       #EBUSD_MQTTCA: "/path/to/cafile"       # Use CERTFILE for MQTT TLS client certificate (no default)       #EBUSD_MQTTCERT: "/path/to/certfile"       # Use KEYFILE for MQTT TLS client certificate (no default)       #EBUSD_MQTTKEY: "/path/to/keyfile"       # Use PASSWORD for the encrypted KEYFILE (no default)       #EBUSD_MQTTKEYPASS: "some-passwort"       # Allow insecure TLS connection (e.g. using a self signed certificate)       #EBUSD_MQTTINSECURE: ""        # KNX options:        # URL to open (i.e. "[multicast][@interface]" for KNXnet/IP)       #EBUSD_KNXURL: ""       # Maximum age in seconds for using the last value of read messages (0=disable)       #EBUSD_KNXRAGE: 30       # Maximum age in seconds for using the last value for reads on write messages (0=disable),       #EBUSD_KNXWAGE: 7200       # Read KNX integration settings from FILE       #EBUSD_KNXINT: "/etc/ebusd/knx.cfg"       # Add variable(s) to the read KNX integration settings       #EBUSD_KNXVAR: "address=1.1.1"      # when using the optional mqtt container below, add the dependency here:     #depends_on:       #- MQTT      restart: unless-stopped

### Operating system

other

### CPU architecture

armv7l

### Dockerized

latest

### Hardware interface

adapter 5 via WiFi

### Related integration

MQTT Home Assistant via mqtt-hassio.cfg

### Logs

Logger: homeassistant.components.mqtt.models
Source: components/sensor/__init__.py:585
Integration: MQTT (documentation, issues)
First occurred: 10:42:42 (4 occurrences)
Last logged: 10:43:02

Exception raised when updating state of sensor.vaillant_scan, topic: 'Vaillant/global/scan' with payload: b'"running"'
Exception raised when updating state of sensor.vaillant_scan, topic: 'Vaillant/global/scan' with payload: b'"finished"'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 581, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '"running"'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 596, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 585, in state
    raise ValueError(
ValueError: Sensor sensor.vaillant_scan has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '"running"' (<class 'str'>)

**Comment by BeFygo** [comment]
With the latest john30/ebusd:devel docker image this issue is patched
